services:
  server:
    image: node:20
    working_dir: /server
    volumes:
      - .:/server
      - server_data:/server_data
    command: sh bin/entrypoint.sh
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    networks:
      - api_network

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - api_network

  redis:
    image: redis
    environment:
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis:/data
    networks:
      - api_network

volumes:
  server_data:
  db_data:
  redis:

networks:
  api_network:
    driver: bridge